<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "magelink"
 *
 * Auto generated by Extension Builder 2013-05-17
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'MageLink',
	'description' => 'Extbase Solution to connect TYPO3 and Magento',
	'category' => 'plugin',
	'author' => 'Bastian Zagar',
	'author_email' => 'zagar@aixdesign.net',
	'author_company' => 'aixdesign.net',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => 'uploads/tx_magelink/',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.3',
	'constraints' => array(
		'depends' => array(
			'typo3'     => '6.1.0-6.2.99',
			'php' 		=> '5.3.3-5.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>